Read module metadata

diff --git a/.github/workflows/publishing-workflow.yml b/.github/workflows/publishing-workflow.yml
--- a/.github/workflows/publishing-workflow.yml
+++ b/.github/workflows/publishing-workflow.yml
@@ -44,12 +44,10 @@ jobs:
             BRANCH_PATH="${{ github.ref_name }}"
           fi
           echo "BRANCH_PATH: $BRANCH_PATH"
-
           # Extract the module path by removing the version part from the branch name
           MODULE_PATH=$(echo "$BRANCH_PATH" | sed -E 's|feature/onboard-avm/||; s|-[0-9]+\.[0-9]+\.[0-9]+$||')
           METADATA_FILE="elements/${MODULE_PATH}/metadata.json"
           echo "Looking for metadata file at $METADATA_FILE"
-
           if [ -f "$METADATA_FILE" ]; then
             MODULE_NAME=$(jq -r '.module_name' "$METADATA_FILE")
             VERSION=$(jq -r '.version' "$METADATA_FILE")
@@ -80,6 +78,28 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.head_ref }}
+      - name: Read module metadata
+        run: |
+          # Determine the branch path based on the event type
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            BRANCH_PATH="${{ github.head_ref }}"
+          else
+            BRANCH_PATH="${{ github.ref_name }}"
+          fi
+          echo "BRANCH_PATH: $BRANCH_PATH"
+          # Extract the module path by removing the version part from the branch name
+          MODULE_PATH=$(echo "$BRANCH_PATH" | sed -E 's|feature/onboard-avm/||; s|-[0-9]+\.[0-9]+\.[0-9]+$||')
+          METADATA_FILE="elements/${MODULE_PATH}/metadata.json"
+          echo "Looking for metadata file at $METADATA_FILE"
+          if [ -f "$METADATA_FILE" ]; then
+            MODULE_NAME=$(jq -r '.module_name' "$METADATA_FILE")
+            VERSION=$(jq -r '.version' "$METADATA_FILE")
+            echo "module_name=$MODULE_NAME" >> $GITHUB_ENV
+            echo "version=$VERSION" >> $GITHUB_ENV
+          else
+            echo "Error: Metadata file not found at $METADATA_FILE"
+            exit 1
+          fi
       - name: Publish Bicep Modules to ACR
         uses: ./.github/actions/templates/publish
         with:
